"""Seed data for 5 simulated patients with varying risk profiles."""

PATIENTS = [
    {
        "patient_id": "P-10001",
        "name": "Margaret Chen",
        "age": 78,
        "gender": "Female",
        "mrn": "MRN-2026-10001",
        "risk_profile": "critical",
        "room": "ICU-412",
        "conditions": [
            "Congestive Heart Failure (CHF)",
            "Type 2 Diabetes",
            "Chronic Kidney Disease Stage 3",
        ],
        "medications": [
            {"name": "Lisinopril", "dose": "20mg", "frequency": "daily"},
            {"name": "Metformin", "dose": "1000mg", "frequency": "twice daily"},
            {"name": "Furosemide", "dose": "40mg", "frequency": "daily"},
            {"name": "Metoprolol", "dose": "50mg", "frequency": "twice daily"},
        ],
        "alert_thresholds": {
            "heart_rate": {"low": 50, "high": 110},
            "blood_pressure_systolic": {"low": 85, "high": 150},
            "blood_pressure_diastolic": {"low": 55, "high": 95},
            "temperature": {"low": 96.5, "high": 100.5},
            "spo2": {"low": 92, "high": 100},
            "respiratory_rate": {"low": 10, "high": 24},
            "blood_glucose": {"low": 80, "high": 200},
        },
        "braden_score": {
            "total": 12,
            "risk_level": "HIGH",
            "subscores": {"sensory_perception": 2, "moisture": 2, "activity": 1, "mobility": 2, "nutrition": 3, "friction_shear": 2},
            "assessed_date": "2026-03-29",
        },
        "fall_risk": {
            "level": "HIGH",
            "factors": ["orthostatic_hypotension", "polypharmacy", "age_over_75", "history_of_dizziness"],
            "last_assessed": "2026-03-29",
        },
    },
    {
        "patient_id": "P-10002",
        "name": "James Rodriguez",
        "age": 65,
        "gender": "Male",
        "mrn": "MRN-2026-10002",
        "risk_profile": "moderate",
        "room": "Floor3-308",
        "conditions": [
            "Hypertension",
            "Post-CABG Surgery (Day 5)",
        ],
        "medications": [
            {"name": "Amlodipine", "dose": "10mg", "frequency": "daily"},
            {"name": "Aspirin", "dose": "81mg", "frequency": "daily"},
            {"name": "Atorvastatin", "dose": "40mg", "frequency": "daily"},
        ],
        "alert_thresholds": {
            "heart_rate": {"low": 55, "high": 105},
            "blood_pressure_systolic": {"low": 90, "high": 145},
            "blood_pressure_diastolic": {"low": 60, "high": 90},
            "temperature": {"low": 97.0, "high": 100.0},
            "spo2": {"low": 93, "high": 100},
            "respiratory_rate": {"low": 11, "high": 22},
            "blood_glucose": {"low": 70, "high": 160},
        },
        "braden_score": {
            "total": 14,
            "risk_level": "MODERATE",
            "subscores": {"sensory_perception": 3, "moisture": 3, "activity": 2, "mobility": 2, "nutrition": 2, "friction_shear": 2},
            "assessed_date": "2026-03-28",
        },
        "fall_risk": {
            "level": "MODERATE",
            "factors": ["post_surgical", "reduced_mobility", "opioid_use"],
            "last_assessed": "2026-03-28",
        },
    },
    {
        "patient_id": "P-10003",
        "name": "Aisha Patel",
        "age": 52,
        "gender": "Female",
        "mrn": "MRN-2026-10003",
        "risk_profile": "moderate",
        "room": "Floor2-215",
        "conditions": [
            "Type 1 Diabetes",
            "Asthma (moderate persistent)",
        ],
        "medications": [
            {"name": "Insulin Glargine", "dose": "24 units", "frequency": "daily"},
            {"name": "Insulin Lispro", "dose": "sliding scale", "frequency": "with meals"},
            {"name": "Fluticasone/Salmeterol", "dose": "250/50mcg", "frequency": "twice daily"},
            {"name": "Albuterol", "dose": "2 puffs", "frequency": "as needed"},
        ],
        "alert_thresholds": {
            "heart_rate": {"low": 58, "high": 105},
            "blood_pressure_systolic": {"low": 90, "high": 140},
            "blood_pressure_diastolic": {"low": 60, "high": 90},
            "temperature": {"low": 97.0, "high": 100.0},
            "spo2": {"low": 93, "high": 100},
            "respiratory_rate": {"low": 12, "high": 22},
            "blood_glucose": {"low": 70, "high": 250},
        },
        "braden_score": {
            "total": 18,
            "risk_level": "LOW",
            "subscores": {"sensory_perception": 3, "moisture": 3, "activity": 3, "mobility": 3, "nutrition": 3, "friction_shear": 3},
            "assessed_date": "2026-03-29",
        },
        "fall_risk": {
            "level": "LOW",
            "factors": ["insulin_use"],
            "last_assessed": "2026-03-29",
        },
    },
    {
        "patient_id": "P-10004",
        "name": "Robert Kim",
        "age": 45,
        "gender": "Male",
        "mrn": "MRN-2026-10004",
        "risk_profile": "stable",
        "room": "Floor1-102",
        "conditions": [
            "Appendectomy Recovery (Day 2)",
        ],
        "medications": [
            {"name": "Acetaminophen", "dose": "500mg", "frequency": "every 6 hours"},
            {"name": "Ondansetron", "dose": "4mg", "frequency": "as needed"},
        ],
        "alert_thresholds": {
            "heart_rate": {"low": 60, "high": 100},
            "blood_pressure_systolic": {"low": 90, "high": 140},
            "blood_pressure_diastolic": {"low": 60, "high": 90},
            "temperature": {"low": 97.0, "high": 100.5},
            "spo2": {"low": 95, "high": 100},
            "respiratory_rate": {"low": 12, "high": 20},
            "blood_glucose": {"low": 70, "high": 140},
        },
        "braden_score": {
            "total": 20,
            "risk_level": "LOW",
            "subscores": {"sensory_perception": 4, "moisture": 3, "activity": 3, "mobility": 4, "nutrition": 3, "friction_shear": 3},
            "assessed_date": "2026-03-29",
        },
        "fall_risk": {
            "level": "LOW",
            "factors": [],
            "last_assessed": "2026-03-29",
        },
    },
    {
        "patient_id": "P-10005",
        "name": "Linda Okafor",
        "age": 34,
        "gender": "Female",
        "mrn": "MRN-2026-10005",
        "risk_profile": "stable",
        "room": "Floor1-118",
        "conditions": [
            "Observation - Mild Pneumonia",
        ],
        "medications": [
            {"name": "Azithromycin", "dose": "500mg", "frequency": "daily"},
            {"name": "Ibuprofen", "dose": "400mg", "frequency": "every 8 hours"},
        ],
        "alert_thresholds": {
            "heart_rate": {"low": 60, "high": 100},
            "blood_pressure_systolic": {"low": 90, "high": 140},
            "blood_pressure_diastolic": {"low": 60, "high": 90},
            "temperature": {"low": 97.0, "high": 101.0},
            "spo2": {"low": 94, "high": 100},
            "respiratory_rate": {"low": 12, "high": 22},
            "blood_glucose": {"low": 70, "high": 140},
        },
        "braden_score": {
            "total": 21,
            "risk_level": "LOW",
            "subscores": {"sensory_perception": 4, "moisture": 4, "activity": 3, "mobility": 4, "nutrition": 3, "friction_shear": 3},
            "assessed_date": "2026-03-30",
        },
        "fall_risk": {
            "level": "LOW",
            "factors": [],
            "last_assessed": "2026-03-30",
        },
    },
]
