"""Seed data for hospital floor inventory with varying stock levels and risk profiles.

Inventory items are correlated with the 5 patients (P-10001 through P-10005)
and their medications/conditions from the patient-monitoring seed data.
"""

INVENTORY_ITEMS = [
    # =============================================
    # ICU FLOOR — High acuity, high burn rates
    # =============================================
    {
        "item_id": "INV-001",
        "item_name": "Heparin 5000U",
        "category": "medication",
        "floor": "ICU",
        "storage_location": "ICU Pyxis Station A",
        "current_stock": 8,
        "par_level": 30,
        "unit": "doses",
        "burn_rate_per_hour": 1.2,
        "last_restocked": "2026-03-30T02:00:00Z",
        "supplier": "Pfizer",
        "lead_time_hours": 4,
        "substitute_items": ["Enoxaparin 40mg"],
        "dependent_patients": ["P-10001"],
        "notes": "Critical anticoagulant. P-10001 on continuous drip. Stock declining rapidly.",
    },
    {
        "item_id": "INV-002",
        "item_name": "IV Start Kit",
        "category": "iv_supply",
        "floor": "ICU",
        "storage_location": "ICU Supply Room B",
        "current_stock": 3,
        "par_level": 20,
        "unit": "kits",
        "burn_rate_per_hour": 0.8,
        "last_restocked": "2026-03-29T18:00:00Z",
        "supplier": "BD Medical",
        "lead_time_hours": 2,
        "substitute_items": [],
        "dependent_patients": ["P-10001", "P-10002"],
        "notes": "No substitute. Required for all IV medication administration.",
    },
    {
        "item_id": "INV-003",
        "item_name": "Furosemide 40mg",
        "category": "medication",
        "floor": "ICU",
        "storage_location": "ICU Pyxis Station A",
        "current_stock": 22,
        "par_level": 25,
        "unit": "doses",
        "burn_rate_per_hour": 0.3,
        "last_restocked": "2026-03-30T06:00:00Z",
        "supplier": "Sanofi",
        "lead_time_hours": 4,
        "substitute_items": ["Bumetanide 1mg"],
        "dependent_patients": ["P-10001"],
        "notes": "Loop diuretic for CHF management. P-10001 on daily dose.",
    },
    {
        "item_id": "INV-004",
        "item_name": "Ventilator Circuit Tubing",
        "category": "respiratory_supply",
        "floor": "ICU",
        "storage_location": "ICU Respiratory Cart",
        "current_stock": 2,
        "par_level": 10,
        "unit": "sets",
        "burn_rate_per_hour": 0.15,
        "last_restocked": "2026-03-29T12:00:00Z",
        "supplier": "Hamilton Medical",
        "lead_time_hours": 6,
        "substitute_items": [],
        "dependent_patients": ["P-10001"],
        "notes": "No substitute. Must match Hamilton C6 ventilator (D-4001). Change every 7 days per protocol.",
    },
    {
        "item_id": "INV-005",
        "item_name": "Pressure Injury Dressing (Mepilex Border)",
        "category": "wound_care",
        "floor": "ICU",
        "storage_location": "ICU Supply Room B",
        "current_stock": 4,
        "par_level": 15,
        "unit": "units",
        "burn_rate_per_hour": 0.2,
        "last_restocked": "2026-03-29T08:00:00Z",
        "supplier": "Molnlycke",
        "lead_time_hours": 8,
        "substitute_items": ["Allevyn Foam Dressing"],
        "dependent_patients": ["P-10001"],
        "notes": "P-10001 has Braden score 12 (HIGH risk). Smart bed D-7001 shows sacral pressure at 48mmHg.",
    },
    {
        "item_id": "INV-006",
        "item_name": "Blood Culture Kit",
        "category": "consumable",
        "floor": "ICU",
        "storage_location": "ICU Lab Station",
        "current_stock": 6,
        "par_level": 12,
        "unit": "kits",
        "burn_rate_per_hour": 0.1,
        "last_restocked": "2026-03-30T04:00:00Z",
        "supplier": "bioMerieux",
        "lead_time_hours": 3,
        "substitute_items": [],
        "dependent_patients": [],
        "notes": "Essential for sepsis workup. No substitute. Must maintain minimum stock for emergency protocols.",
    },

    # =============================================
    # FLOOR 3 — Post-surgical, moderate acuity
    # =============================================
    {
        "item_id": "INV-007",
        "item_name": "Aspirin 81mg",
        "category": "medication",
        "floor": "Floor3",
        "storage_location": "Floor3 Pyxis Station",
        "current_stock": 45,
        "par_level": 50,
        "unit": "doses",
        "burn_rate_per_hour": 0.2,
        "last_restocked": "2026-03-30T06:00:00Z",
        "supplier": "Bayer",
        "lead_time_hours": 4,
        "substitute_items": [],
        "dependent_patients": ["P-10002"],
        "notes": "Post-CABG antiplatelet therapy. P-10002 on daily dose. Adequate stock.",
    },
    {
        "item_id": "INV-008",
        "item_name": "Surgical Wound Dressing Kit",
        "category": "wound_care",
        "floor": "Floor3",
        "storage_location": "Floor3 Supply Room",
        "current_stock": 5,
        "par_level": 20,
        "unit": "kits",
        "burn_rate_per_hour": 0.4,
        "last_restocked": "2026-03-29T14:00:00Z",
        "supplier": "3M Healthcare",
        "lead_time_hours": 3,
        "substitute_items": ["Standard Gauze + Tegaderm"],
        "dependent_patients": ["P-10002"],
        "notes": "Post-CABG wound care. P-10002 requires dressing changes BID. Stock declining.",
    },
    {
        "item_id": "INV-009",
        "item_name": "Atorvastatin 40mg",
        "category": "medication",
        "floor": "Floor3",
        "storage_location": "Floor3 Pyxis Station",
        "current_stock": 30,
        "par_level": 30,
        "unit": "doses",
        "burn_rate_per_hour": 0.1,
        "last_restocked": "2026-03-30T06:00:00Z",
        "supplier": "Pfizer",
        "lead_time_hours": 4,
        "substitute_items": ["Rosuvastatin 20mg"],
        "dependent_patients": ["P-10002"],
        "notes": "Statin therapy. Adequate stock.",
    },

    # =============================================
    # FLOOR 2 — General medical
    # =============================================
    {
        "item_id": "INV-010",
        "item_name": "Metformin 1000mg",
        "category": "medication",
        "floor": "Floor2",
        "storage_location": "Floor2 Pyxis Station",
        "current_stock": 18,
        "par_level": 20,
        "unit": "doses",
        "burn_rate_per_hour": 0.15,
        "last_restocked": "2026-03-30T06:00:00Z",
        "supplier": "Merck",
        "lead_time_hours": 4,
        "substitute_items": ["Glipizide 5mg"],
        "dependent_patients": ["P-10003"],
        "notes": "Diabetes management. P-10003 on twice daily dosing.",
    },
    {
        "item_id": "INV-011",
        "item_name": "Infusion Pump Tubing Set",
        "category": "iv_supply",
        "floor": "Floor2",
        "storage_location": "Floor2 Supply Room",
        "current_stock": 4,
        "par_level": 15,
        "unit": "sets",
        "burn_rate_per_hour": 0.3,
        "last_restocked": "2026-03-29T20:00:00Z",
        "supplier": "BD Medical",
        "lead_time_hours": 2,
        "substitute_items": [],
        "dependent_patients": ["P-10003"],
        "notes": "Required for infusion pump D-3002. No substitute — must match BD Alaris 8015.",
    },
    {
        "item_id": "INV-012",
        "item_name": "Nitrile Gloves (Medium)",
        "category": "ppe",
        "floor": "Floor2",
        "storage_location": "Floor2 PPE Station",
        "current_stock": 150,
        "par_level": 500,
        "unit": "pairs",
        "burn_rate_per_hour": 8.0,
        "last_restocked": "2026-03-29T06:00:00Z",
        "supplier": "Halyard Health",
        "lead_time_hours": 6,
        "substitute_items": ["Nitrile Gloves (Large)", "Vinyl Gloves (Medium)"],
        "dependent_patients": [],
        "notes": "General PPE. Burn rate high during shift changes. Stock declining.",
    },

    # =============================================
    # FLOOR 1 — Recovery / observation
    # =============================================
    {
        "item_id": "INV-013",
        "item_name": "Lisinopril 10mg",
        "category": "medication",
        "floor": "Floor1",
        "storage_location": "Floor1 Pyxis Station",
        "current_stock": 25,
        "par_level": 25,
        "unit": "doses",
        "burn_rate_per_hour": 0.08,
        "last_restocked": "2026-03-30T06:00:00Z",
        "supplier": "Lupin Pharma",
        "lead_time_hours": 4,
        "substitute_items": ["Enalapril 10mg"],
        "dependent_patients": ["P-10004"],
        "notes": "ACE inhibitor for hypertension. P-10004 on daily dose. Full stock.",
    },
    {
        "item_id": "INV-014",
        "item_name": "Glucose Test Strips",
        "category": "consumable",
        "floor": "Floor1",
        "storage_location": "Floor1 Nursing Station",
        "current_stock": 20,
        "par_level": 100,
        "unit": "strips",
        "burn_rate_per_hour": 1.5,
        "last_restocked": "2026-03-29T10:00:00Z",
        "supplier": "Abbott",
        "lead_time_hours": 2,
        "substitute_items": [],
        "dependent_patients": ["P-10004", "P-10005"],
        "notes": "Required for diabetic monitoring. P-10004 and P-10005 both require QID glucose checks. Stock critically low.",
    },
    {
        "item_id": "INV-015",
        "item_name": "Albuterol Nebulizer Solution",
        "category": "respiratory_supply",
        "floor": "Floor1",
        "storage_location": "Floor1 Respiratory Cart",
        "current_stock": 10,
        "par_level": 20,
        "unit": "vials",
        "burn_rate_per_hour": 0.25,
        "last_restocked": "2026-03-30T02:00:00Z",
        "supplier": "Nephron Pharma",
        "lead_time_hours": 4,
        "substitute_items": ["Levalbuterol 0.63mg"],
        "dependent_patients": ["P-10005"],
        "notes": "P-10005 has COPD with PRN nebulizer treatments. Moderate stock.",
    },
    {
        "item_id": "INV-016",
        "item_name": "Discharge Supply Kit",
        "category": "consumable",
        "floor": "Floor1",
        "storage_location": "Floor1 Discharge Prep Area",
        "current_stock": 1,
        "par_level": 8,
        "unit": "kits",
        "burn_rate_per_hour": 0.1,
        "last_restocked": "2026-03-28T14:00:00Z",
        "supplier": "Medline",
        "lead_time_hours": 12,
        "substitute_items": [],
        "dependent_patients": ["P-10004", "P-10005"],
        "notes": "Contains wound care supplies, medication organizer, patient education materials. Only 1 kit left, 2 patients pending discharge.",
    },
]


# =============================================
# INVENTORY TRANSACTIONS — recent usage history
# =============================================

INVENTORY_TRANSACTIONS = [
    {"item_id": "INV-001", "transaction_type": "dispensed", "quantity": 2, "timestamp": "2026-03-30T06:00:00Z", "floor": "ICU", "patient_id": "P-10001", "dispensed_by": "RN Maria Santos"},
    {"item_id": "INV-001", "transaction_type": "dispensed", "quantity": 2, "timestamp": "2026-03-30T04:00:00Z", "floor": "ICU", "patient_id": "P-10001", "dispensed_by": "RN Maria Santos"},
    {"item_id": "INV-001", "transaction_type": "dispensed", "quantity": 2, "timestamp": "2026-03-30T02:00:00Z", "floor": "ICU", "patient_id": "P-10001", "dispensed_by": "RN David Park"},
    {"item_id": "INV-002", "transaction_type": "dispensed", "quantity": 1, "timestamp": "2026-03-30T05:30:00Z", "floor": "ICU", "patient_id": "P-10001", "dispensed_by": "RN Maria Santos"},
    {"item_id": "INV-002", "transaction_type": "dispensed", "quantity": 1, "timestamp": "2026-03-30T03:00:00Z", "floor": "ICU", "patient_id": "P-10002", "dispensed_by": "RN David Park"},
    {"item_id": "INV-004", "transaction_type": "dispensed", "quantity": 1, "timestamp": "2026-03-29T14:00:00Z", "floor": "ICU", "patient_id": "P-10001", "dispensed_by": "RT Sarah Kim"},
    {"item_id": "INV-005", "transaction_type": "dispensed", "quantity": 2, "timestamp": "2026-03-30T01:00:00Z", "floor": "ICU", "patient_id": "P-10001", "dispensed_by": "RN Maria Santos"},
    {"item_id": "INV-008", "transaction_type": "dispensed", "quantity": 1, "timestamp": "2026-03-30T06:00:00Z", "floor": "Floor3", "patient_id": "P-10002", "dispensed_by": "RN Lisa Chen"},
    {"item_id": "INV-008", "transaction_type": "dispensed", "quantity": 1, "timestamp": "2026-03-29T18:00:00Z", "floor": "Floor3", "patient_id": "P-10002", "dispensed_by": "RN Lisa Chen"},
    {"item_id": "INV-011", "transaction_type": "dispensed", "quantity": 1, "timestamp": "2026-03-30T04:00:00Z", "floor": "Floor2", "patient_id": "P-10003", "dispensed_by": "RN James Wu"},
    {"item_id": "INV-012", "transaction_type": "dispensed", "quantity": 30, "timestamp": "2026-03-30T06:00:00Z", "floor": "Floor2", "patient_id": None, "dispensed_by": "Shift Change"},
    {"item_id": "INV-014", "transaction_type": "dispensed", "quantity": 4, "timestamp": "2026-03-30T06:00:00Z", "floor": "Floor1", "patient_id": "P-10004", "dispensed_by": "RN Amy Torres"},
    {"item_id": "INV-014", "transaction_type": "dispensed", "quantity": 4, "timestamp": "2026-03-30T06:00:00Z", "floor": "Floor1", "patient_id": "P-10005", "dispensed_by": "RN Amy Torres"},
    {"item_id": "INV-016", "transaction_type": "dispensed", "quantity": 1, "timestamp": "2026-03-29T16:00:00Z", "floor": "Floor1", "patient_id": None, "dispensed_by": "Discharge Coordinator"},
    {"item_id": "INV-001", "transaction_type": "restocked", "quantity": 20, "timestamp": "2026-03-30T02:00:00Z", "floor": "ICU", "patient_id": None, "dispensed_by": "Pharmacy"},
    {"item_id": "INV-008", "transaction_type": "restocked", "quantity": 10, "timestamp": "2026-03-29T14:00:00Z", "floor": "Floor3", "patient_id": None, "dispensed_by": "Central Supply"},
]
