"""Seed data for multi-site hospital network, service contracts, and field service visits.

Represents a medical device company's view across 3 hospital customers.
Site-001 is the existing Connected Care hospital (Memorial General).
"""

SITES = [
    {
        "site_id": "site-001",
        "site_name": "Memorial General Hospital",
        "city": "Boston",
        "state": "MA",
        "bed_count": 450,
        "account_manager": "Sarah Mitchell",
        "tier": "Strategic",
        "go_live_date": "2023-05-01",
    },
    {
        "site_id": "site-002",
        "site_name": "Riverside Community Hospital",
        "city": "Hartford",
        "state": "CT",
        "bed_count": 180,
        "account_manager": "Sarah Mitchell",
        "tier": "Growth",
        "go_live_date": "2024-02-15",
    },
    {
        "site_id": "site-003",
        "site_name": "Lakewood Surgical Center",
        "city": "Providence",
        "state": "RI",
        "bed_count": 60,
        "account_manager": "Tom Bradley",
        "tier": "Standard",
        "go_live_date": "2025-01-10",
    },
]

SERVICE_CONTRACTS = [
    {
        "contract_id": "SC-001",
        "site_id": "site-001",
        "site_name": "Memorial General Hospital",
        "contract_type": "Premium",
        "start_date": "2024-04-01",
        "end_date": "2027-03-31",
        "renewal_date": "2027-03-31",
        "annual_value": 285000,
        "sla_response_hours": 4,
        "includes_parts": True,
        "includes_firmware": True,
        "status": "active",
    },
    {
        "contract_id": "SC-002",
        "site_id": "site-002",
        "site_name": "Riverside Community Hospital",
        "contract_type": "Standard",
        "start_date": "2024-06-01",
        "end_date": "2026-05-31",
        "renewal_date": "2026-05-31",
        "annual_value": 95000,
        "sla_response_hours": 8,
        "includes_parts": False,
        "includes_firmware": True,
        "status": "active",
        "notes": "Renewal in 60 days. Hospital evaluating competitor bids.",
    },
    {
        "contract_id": "SC-003",
        "site_id": "site-003",
        "site_name": "Lakewood Surgical Center",
        "contract_type": "Basic",
        "start_date": "2025-01-10",
        "end_date": "2026-01-09",
        "renewal_date": "2026-01-09",
        "annual_value": 35000,
        "sla_response_hours": 24,
        "includes_parts": False,
        "includes_firmware": False,
        "status": "expired",
        "notes": "Contract expired. No renewal initiated. Possible churn risk.",
    },
]

# Devices at site-002 and site-003 (site-001 devices already exist in device-management seed)
MULTI_SITE_DEVICES = [
    # =============================================
    # SITE-002: Riverside Community Hospital
    # =============================================
    {
        "device_id": "D-8001",
        "site_id": "site-002",
        "device_type": "vital_signs_monitor",
        "model": "Philips IntelliVue MX800",
        "serial_number": "VSM-2026-R01",
        "location": "MedSurg-201",
        "floor": "MedSurg",
        "firmware_version": "3.1.0",
        "latest_firmware": "3.2.1",
        "installation_date": "2024-03-10",
        "last_maintenance_date": "2025-09-15",
        "status": "active",
        "risk_profile": "moderate",
        "notes": "Firmware behind. Connectivity drops during peak hours.",
    },
    {
        "device_id": "D-8002",
        "site_id": "site-002",
        "device_type": "vital_signs_monitor",
        "model": "GE CARESCAPE B650",
        "serial_number": "VSM-2026-R02",
        "location": "ED-105",
        "floor": "ED",
        "firmware_version": "4.0.2",
        "latest_firmware": "4.0.2",
        "installation_date": "2025-06-01",
        "last_maintenance_date": "2026-02-20",
        "status": "active",
        "risk_profile": "healthy",
        "notes": "Recently installed. All nominal.",
    },
    {
        "device_id": "D-8003",
        "site_id": "site-002",
        "device_type": "infusion_pump",
        "model": "BD Alaris 8015",
        "serial_number": "INF-2026-R01",
        "location": "MedSurg-201",
        "floor": "MedSurg",
        "firmware_version": "9.19.1",
        "latest_firmware": "9.33.0",
        "installation_date": "2023-08-20",
        "last_maintenance_date": "2025-05-10",
        "status": "active",
        "risk_profile": "critical",
        "notes": "Firmware severely outdated. Occlusion errors increasing. Overdue for service.",
    },
    {
        "device_id": "D-8004",
        "site_id": "site-002",
        "device_type": "infusion_pump",
        "model": "BD Alaris 8015",
        "serial_number": "INF-2026-R02",
        "location": "ED-105",
        "floor": "ED",
        "firmware_version": "9.28.0",
        "latest_firmware": "9.33.0",
        "installation_date": "2024-11-01",
        "last_maintenance_date": "2026-01-15",
        "status": "active",
        "risk_profile": "moderate",
        "notes": "One firmware version behind. Battery showing early wear.",
    },
    {
        "device_id": "D-8005",
        "site_id": "site-002",
        "device_type": "ventilator",
        "model": "Hamilton C6",
        "serial_number": "VNT-2026-R01",
        "location": "ICU-110",
        "floor": "ICU",
        "firmware_version": "2.8.0",
        "latest_firmware": "3.1.0",
        "installation_date": "2023-12-01",
        "last_maintenance_date": "2025-07-20",
        "status": "active",
        "risk_profile": "critical",
        "notes": "High usage. Calibration drift at 5.8%. Needs immediate service.",
    },
    {
        "device_id": "D-8006",
        "site_id": "site-002",
        "device_type": "ventilator",
        "model": "Draeger Evita V800",
        "serial_number": "VNT-2026-R02",
        "location": "ICU-110",
        "floor": "ICU",
        "firmware_version": "1.5.2",
        "latest_firmware": "1.5.2",
        "installation_date": "2025-08-15",
        "last_maintenance_date": "2026-03-01",
        "status": "active",
        "risk_profile": "healthy",
        "notes": "New unit. Excellent metrics.",
    },
    {
        "device_id": "D-8007",
        "site_id": "site-002",
        "device_type": "wearable",
        "model": "BioStamp nPoint",
        "serial_number": "WRB-2026-R01",
        "location": "MedSurg-215",
        "floor": "MedSurg",
        "firmware_version": "2.0.1",
        "latest_firmware": "2.1.0",
        "installation_date": "2024-10-01",
        "last_maintenance_date": "2025-11-20",
        "status": "active",
        "risk_profile": "moderate",
        "notes": "Firmware update available. Signal occasionally weak.",
    },
    # =============================================
    # SITE-003: Lakewood Surgical Center
    # =============================================
    {
        "device_id": "D-9001",
        "site_id": "site-003",
        "device_type": "vital_signs_monitor",
        "model": "Philips IntelliVue MX800",
        "serial_number": "VSM-2026-L01",
        "location": "OR-1",
        "floor": "OR",
        "firmware_version": "3.0.0",
        "latest_firmware": "3.2.1",
        "installation_date": "2025-01-15",
        "last_maintenance_date": "2025-12-01",
        "status": "active",
        "risk_profile": "moderate",
        "notes": "Two firmware versions behind. No service contract active.",
    },
    {
        "device_id": "D-9002",
        "site_id": "site-003",
        "device_type": "infusion_pump",
        "model": "Baxter Sigma Spectrum",
        "serial_number": "INF-2026-L01",
        "location": "OR-1",
        "floor": "OR",
        "firmware_version": "8.0.0",
        "latest_firmware": "8.0.0",
        "installation_date": "2025-02-01",
        "last_maintenance_date": "2026-02-15",
        "status": "active",
        "risk_profile": "healthy",
        "notes": "Current firmware. Good condition.",
    },
    {
        "device_id": "D-9003",
        "site_id": "site-003",
        "device_type": "infusion_pump",
        "model": "BD Alaris 8015",
        "serial_number": "INF-2026-L02",
        "location": "PACU-3",
        "floor": "PACU",
        "firmware_version": "9.19.1",
        "latest_firmware": "9.33.0",
        "installation_date": "2024-01-10",
        "last_maintenance_date": "2025-04-20",
        "status": "active",
        "risk_profile": "critical",
        "notes": "Firmware severely outdated. Error count rising. No active service contract.",
    },
    {
        "device_id": "D-9004",
        "site_id": "site-003",
        "device_type": "ventilator",
        "model": "Hamilton C6",
        "serial_number": "VNT-2026-L01",
        "location": "OR-2",
        "floor": "OR",
        "firmware_version": "3.0.0",
        "latest_firmware": "3.1.0",
        "installation_date": "2025-03-01",
        "last_maintenance_date": "2026-01-10",
        "status": "active",
        "risk_profile": "moderate",
        "notes": "One firmware version behind. Moderate usage.",
    },
    {
        "device_id": "D-9005",
        "site_id": "site-003",
        "device_type": "wearable",
        "model": "Masimo Radius PPG",
        "serial_number": "WRB-2026-L01",
        "location": "PACU-3",
        "floor": "PACU",
        "firmware_version": "5.3.0",
        "latest_firmware": "5.3.0",
        "installation_date": "2025-06-01",
        "last_maintenance_date": "2026-03-10",
        "status": "active",
        "risk_profile": "healthy",
        "notes": "SpO2 wearable. Excellent accuracy.",
    },
]

FIELD_SERVICE_VISITS = [
    {
        "visit_id": "FSV-001",
        "site_id": "site-001",
        "site_name": "Memorial General Hospital",
        "engineer": "Mike Chen",
        "visit_date": "2026-01-10",
        "devices_serviced": ["D-2001", "D-3001", "D-4001"],
        "visit_type": "preventive",
        "duration_hours": 6,
        "parts_used": ["Calibration kit", "Battery pack", "Firmware USB"],
        "outcome": "completed",
        "notes": "Calibrated D-2001 and D-4001. Updated firmware on D-3001 from 9.19 to 9.28. Battery replaced on D-2001.",
    },
    {
        "visit_id": "FSV-002",
        "site_id": "site-001",
        "site_name": "Memorial General Hospital",
        "engineer": "Mike Chen",
        "visit_date": "2025-08-15",
        "devices_serviced": ["D-3001"],
        "visit_type": "corrective",
        "duration_hours": 3,
        "parts_used": ["Occlusion sensor assembly"],
        "outcome": "completed",
        "notes": "Replaced occlusion sensor on D-3001. Error count was at 45. Post-repair error count: 0.",
    },
    {
        "visit_id": "FSV-003",
        "site_id": "site-002",
        "site_name": "Riverside Community Hospital",
        "engineer": "Lisa Park",
        "visit_date": "2025-09-15",
        "devices_serviced": ["D-8001", "D-8003"],
        "visit_type": "preventive",
        "duration_hours": 4,
        "parts_used": ["Calibration kit"],
        "outcome": "completed",
        "notes": "Routine PM on monitors and pumps. D-8003 firmware update deferred — hospital IT scheduling conflict.",
    },
    {
        "visit_id": "FSV-004",
        "site_id": "site-002",
        "site_name": "Riverside Community Hospital",
        "engineer": "Lisa Park",
        "visit_date": "2025-07-20",
        "devices_serviced": ["D-8005"],
        "visit_type": "corrective",
        "duration_hours": 5,
        "parts_used": ["Flow sensor", "Calibration kit"],
        "outcome": "completed",
        "notes": "Flow sensor replacement on Hamilton C6. Calibration drift was at 7.1%. Post-repair: 0.3%.",
    },
    {
        "visit_id": "FSV-005",
        "site_id": "site-003",
        "site_name": "Lakewood Surgical Center",
        "engineer": "Mike Chen",
        "visit_date": "2025-12-01",
        "devices_serviced": ["D-9001"],
        "visit_type": "preventive",
        "duration_hours": 2,
        "parts_used": [],
        "outcome": "completed",
        "notes": "Routine check. Recommended firmware update — site declined due to expired service contract.",
    },
    {
        "visit_id": "FSV-006",
        "site_id": "site-003",
        "site_name": "Lakewood Surgical Center",
        "engineer": "Mike Chen",
        "visit_date": "2025-04-20",
        "devices_serviced": ["D-9003"],
        "visit_type": "corrective",
        "duration_hours": 3,
        "parts_used": ["Occlusion sensor assembly"],
        "outcome": "partial",
        "notes": "Replaced sensor but firmware update needed. Site has no active contract — billable visit. Hospital pushed back on cost.",
    },
]

# Telemetry for multi-site devices (mirrors the structure in device-management seed)
MULTI_SITE_TELEMETRY = [
    # Site-002 devices
    {"device_id": "D-8001", "telemetry": {"battery_level": 65, "connectivity_status": "intermittent", "sensor_accuracy": 91, "error_count": 18, "calibration_drift": 2.1, "device_temperature": 38, "memory_usage": 55, "signal_strength": -62, "uptime_hours": 14200, "usage_cycles": 8500}},
    {"device_id": "D-8002", "telemetry": {"battery_level": 95, "connectivity_status": "connected", "sensor_accuracy": 98, "error_count": 2, "calibration_drift": 0.3, "device_temperature": 34, "memory_usage": 30, "signal_strength": -45, "uptime_hours": 3200, "usage_cycles": 2100}},
    {"device_id": "D-8003", "telemetry": {"battery_level": 35, "connectivity_status": "connected", "sensor_accuracy": 86, "error_count": 58, "calibration_drift": 1.8, "device_temperature": 42, "memory_usage": 78, "signal_strength": -55, "uptime_hours": 22000, "usage_cycles": 15200}},
    {"device_id": "D-8004", "telemetry": {"battery_level": 72, "connectivity_status": "connected", "sensor_accuracy": 94, "error_count": 11, "calibration_drift": 1.2, "device_temperature": 36, "memory_usage": 45, "signal_strength": -50, "uptime_hours": 8500, "usage_cycles": 5800}},
    {"device_id": "D-8005", "telemetry": {"battery_level": 28, "connectivity_status": "connected", "sensor_accuracy": 84, "error_count": 72, "calibration_drift": 5.8, "device_temperature": 48, "memory_usage": 82, "signal_strength": -58, "uptime_hours": 19500, "usage_cycles": 12800}},
    {"device_id": "D-8006", "telemetry": {"battery_level": 97, "connectivity_status": "connected", "sensor_accuracy": 99, "error_count": 1, "calibration_drift": 0.1, "device_temperature": 33, "memory_usage": 22, "signal_strength": -42, "uptime_hours": 2800, "usage_cycles": 1500}},
    {"device_id": "D-8007", "telemetry": {"battery_level": 58, "connectivity_status": "connected", "sensor_accuracy": 92, "error_count": 8, "calibration_drift": 0.9, "device_temperature": 35, "memory_usage": 40, "signal_strength": -68, "uptime_hours": 10200, "usage_cycles": 7200}},
    # Site-003 devices
    {"device_id": "D-9001", "telemetry": {"battery_level": 70, "connectivity_status": "connected", "sensor_accuracy": 90, "error_count": 22, "calibration_drift": 2.8, "device_temperature": 39, "memory_usage": 60, "signal_strength": -58, "uptime_hours": 8800, "usage_cycles": 5500}},
    {"device_id": "D-9002", "telemetry": {"battery_level": 88, "connectivity_status": "connected", "sensor_accuracy": 97, "error_count": 3, "calibration_drift": 0.4, "device_temperature": 34, "memory_usage": 28, "signal_strength": -48, "uptime_hours": 5200, "usage_cycles": 3400}},
    {"device_id": "D-9003", "telemetry": {"battery_level": 30, "connectivity_status": "connected", "sensor_accuracy": 83, "error_count": 65, "calibration_drift": 2.2, "device_temperature": 44, "memory_usage": 85, "signal_strength": -60, "uptime_hours": 18500, "usage_cycles": 13200}},
    {"device_id": "D-9004", "telemetry": {"battery_level": 80, "connectivity_status": "connected", "sensor_accuracy": 95, "error_count": 9, "calibration_drift": 1.5, "device_temperature": 36, "memory_usage": 42, "signal_strength": -52, "uptime_hours": 6200, "usage_cycles": 4100}},
    {"device_id": "D-9005", "telemetry": {"battery_level": 92, "connectivity_status": "connected", "sensor_accuracy": 99, "error_count": 1, "calibration_drift": 0.2, "device_temperature": 33, "memory_usage": 18, "signal_strength": -40, "uptime_hours": 3800, "usage_cycles": 2600}},
]
