"""Seed data for 15 simulated medical devices with varying risk profiles."""

DEVICES = [
    # =============================================
    # VITAL SIGNS MONITORS (3 devices)
    # =============================================
    {
        "device_id": "D-2001",
        "device_type": "vital_signs_monitor",
        "model": "Philips IntelliVue MX800",
        "serial_number": "VSM-2026-001",
        "location": "ICU-412",
        "floor": "ICU",
        "firmware_version": "3.2.1",
        "latest_firmware": "3.2.1",
        "installation_date": "2024-06-15",
        "last_maintenance_date": "2026-01-10",
        "status": "active",
        "risk_profile": "critical",
        "notes": "Intermittent sensor drift detected. Battery degrading rapidly.",
    },
    {
        "device_id": "D-2002",
        "device_type": "vital_signs_monitor",
        "model": "Philips IntelliVue MX800",
        "serial_number": "VSM-2026-002",
        "location": "Floor3-308",
        "floor": "Floor3",
        "firmware_version": "3.1.0",
        "latest_firmware": "3.2.1",
        "installation_date": "2024-09-20",
        "last_maintenance_date": "2025-11-05",
        "status": "active",
        "risk_profile": "moderate",
        "notes": "Firmware one version behind. Occasional connectivity drops.",
    },
    {
        "device_id": "D-2003",
        "device_type": "vital_signs_monitor",
        "model": "GE CARESCAPE B650",
        "serial_number": "VSM-2026-003",
        "location": "Floor1-102",
        "floor": "Floor1",
        "firmware_version": "4.0.2",
        "latest_firmware": "4.0.2",
        "installation_date": "2025-03-01",
        "last_maintenance_date": "2026-02-28",
        "status": "active",
        "risk_profile": "healthy",
        "notes": "Recently serviced. All metrics nominal.",
    },
    # =============================================
    # INFUSION PUMPS (3 devices)
    # =============================================
    {
        "device_id": "D-3001",
        "device_type": "infusion_pump",
        "model": "BD Alaris 8015",
        "serial_number": "INF-2026-001",
        "location": "ICU-412",
        "floor": "ICU",
        "firmware_version": "9.19.1",
        "latest_firmware": "9.33.0",
        "installation_date": "2023-11-10",
        "last_maintenance_date": "2025-08-15",
        "status": "active",
        "risk_profile": "critical",
        "notes": "Firmware significantly outdated. Increasing occlusion sensor errors.",
    },
    {
        "device_id": "D-3002",
        "device_type": "infusion_pump",
        "model": "BD Alaris 8015",
        "serial_number": "INF-2026-002",
        "location": "Floor2-215",
        "floor": "Floor2",
        "firmware_version": "9.28.0",
        "latest_firmware": "9.33.0",
        "installation_date": "2024-07-22",
        "last_maintenance_date": "2025-12-01",
        "status": "active",
        "risk_profile": "moderate",
        "notes": "Minor firmware gap. Battery showing early wear signs.",
    },
    {
        "device_id": "D-3003",
        "device_type": "infusion_pump",
        "model": "Baxter Sigma Spectrum",
        "serial_number": "INF-2026-003",
        "location": "Floor1-118",
        "floor": "Floor1",
        "firmware_version": "8.0.0",
        "latest_firmware": "8.0.0",
        "installation_date": "2025-06-10",
        "last_maintenance_date": "2026-03-01",
        "status": "active",
        "risk_profile": "healthy",
        "notes": "New unit. All systems nominal.",
    },

    # =============================================
    # VENTILATORS (3 devices)
    # =============================================
    {
        "device_id": "D-4001",
        "device_type": "ventilator",
        "model": "Hamilton C6",
        "serial_number": "VNT-2026-001",
        "location": "ICU-412",
        "floor": "ICU",
        "firmware_version": "2.8.0",
        "latest_firmware": "3.1.0",
        "installation_date": "2023-05-18",
        "last_maintenance_date": "2025-06-20",
        "status": "active",
        "risk_profile": "critical",
        "notes": "High usage hours. Flow sensor calibration drifting. Overdue for maintenance.",
    },
    {
        "device_id": "D-4002",
        "device_type": "ventilator",
        "model": "Hamilton C6",
        "serial_number": "VNT-2026-002",
        "location": "Floor3-310",
        "floor": "Floor3",
        "firmware_version": "3.0.0",
        "latest_firmware": "3.1.0",
        "installation_date": "2024-08-05",
        "last_maintenance_date": "2026-01-15",
        "status": "active",
        "risk_profile": "moderate",
        "notes": "One firmware version behind. Moderate usage.",
    },
    {
        "device_id": "D-4003",
        "device_type": "ventilator",
        "model": "Draeger Evita V800",
        "serial_number": "VNT-2026-003",
        "location": "Floor2-220",
        "floor": "Floor2",
        "firmware_version": "1.5.2",
        "latest_firmware": "1.5.2",
        "installation_date": "2025-09-12",
        "last_maintenance_date": "2026-03-10",
        "status": "active",
        "risk_profile": "healthy",
        "notes": "Recently installed. Excellent performance metrics.",
    },
    # =============================================
    # WEARABLES (3 devices)
    # =============================================
    {
        "device_id": "D-5001",
        "device_type": "wearable",
        "model": "BioStamp nPoint",
        "serial_number": "WRB-2026-001",
        "location": "Floor3-308",
        "floor": "Floor3",
        "firmware_version": "2.1.0",
        "latest_firmware": "2.1.0",
        "installation_date": "2025-01-20",
        "last_maintenance_date": "2026-02-10",
        "status": "active",
        "risk_profile": "healthy",
        "notes": "Patient-worn accelerometer + HR. Good battery life.",
    },
    {
        "device_id": "D-5002",
        "device_type": "wearable",
        "model": "BioStamp nPoint",
        "serial_number": "WRB-2026-002",
        "location": "Floor2-215",
        "floor": "Floor2",
        "firmware_version": "2.0.1",
        "latest_firmware": "2.1.0",
        "installation_date": "2024-11-15",
        "last_maintenance_date": "2025-10-20",
        "status": "active",
        "risk_profile": "moderate",
        "notes": "Firmware update available. Signal strength occasionally weak.",
    },
    {
        "device_id": "D-5003",
        "device_type": "wearable",
        "model": "Masimo Radius PPG",
        "serial_number": "WRB-2026-003",
        "location": "Floor1-102",
        "floor": "Floor1",
        "firmware_version": "5.3.0",
        "latest_firmware": "5.3.0",
        "installation_date": "2025-07-01",
        "last_maintenance_date": "2026-03-05",
        "status": "active",
        "risk_profile": "healthy",
        "notes": "SpO2 wearable. Excellent accuracy.",
    },

    # =============================================
    # SMART HOME SENSORS (3 devices)
    # =============================================
    {
        "device_id": "D-6001",
        "device_type": "smart_home_sensor",
        "model": "CarePredict Tempo",
        "serial_number": "SHS-2026-001",
        "location": "Floor1-102",
        "floor": "Floor1",
        "firmware_version": "1.8.0",
        "latest_firmware": "1.8.0",
        "installation_date": "2025-04-10",
        "last_maintenance_date": "2026-01-25",
        "status": "active",
        "risk_profile": "healthy",
        "notes": "Bed sensor. Monitors sleep patterns and bed exits.",
    },
    {
        "device_id": "D-6002",
        "device_type": "smart_home_sensor",
        "model": "Vayyar Home",
        "serial_number": "SHS-2026-002",
        "location": "Floor1-118",
        "floor": "Floor1",
        "firmware_version": "3.2.0",
        "latest_firmware": "3.4.0",
        "installation_date": "2024-12-01",
        "last_maintenance_date": "2025-09-15",
        "status": "active",
        "risk_profile": "moderate",
        "notes": "Room presence and fall detection sensor. Firmware behind.",
    },
    {
        "device_id": "D-6003",
        "device_type": "smart_home_sensor",
        "model": "Withings Sleep Analyzer",
        "serial_number": "SHS-2026-003",
        "location": "Floor3-310",
        "floor": "Floor3",
        "firmware_version": "2.0.5",
        "latest_firmware": "2.0.5",
        "installation_date": "2025-08-20",
        "last_maintenance_date": "2026-02-20",
        "status": "active",
        "risk_profile": "healthy",
        "notes": "Under-mattress sleep and respiratory monitor. Nominal.",
    },

    # =============================================
    # SMART BEDS (5 devices — one per patient room)
    # =============================================
    {
        "device_id": "D-7001",
        "device_type": "smart_bed",
        "model": "Baxter Progressa",
        "serial_number": "SBD-2026-001",
        "location": "ICU-412",
        "floor": "ICU",
        "firmware_version": "4.1.0",
        "latest_firmware": "4.1.0",
        "installation_date": "2024-03-10",
        "last_maintenance_date": "2026-02-15",
        "status": "active",
        "risk_profile": "healthy",
        "notes": "ICU smart bed. Pressure mapping, bed exit detection, head-of-bed angle monitoring. Assigned to P-10001.",
        "assigned_patient_id": "P-10001",
        "bed_capabilities": ["pressure_mapping", "bed_exit_detection", "head_of_bed_angle", "weight_sensing", "turn_assist"],
    },
    {
        "device_id": "D-7002",
        "device_type": "smart_bed",
        "model": "Baxter Progressa",
        "serial_number": "SBD-2026-002",
        "location": "Floor3-308",
        "floor": "Floor3",
        "firmware_version": "3.8.2",
        "latest_firmware": "3.9.0",
        "installation_date": "2024-07-22",
        "last_maintenance_date": "2025-12-10",
        "status": "active",
        "risk_profile": "moderate",
        "notes": "Post-surgical floor bed. Firmware one version behind. Assigned to P-10002.",
        "assigned_patient_id": "P-10002",
        "bed_capabilities": ["pressure_mapping", "bed_exit_detection", "head_of_bed_angle", "turn_assist"],
    },
    {
        "device_id": "D-7003",
        "device_type": "smart_bed",
        "model": "Baxter Progressa",
        "serial_number": "SBD-2026-003",
        "location": "Floor2-215",
        "floor": "Floor2",
        "firmware_version": "3.9.0",
        "latest_firmware": "3.9.0",
        "installation_date": "2025-01-15",
        "last_maintenance_date": "2026-03-01",
        "status": "active",
        "risk_profile": "healthy",
        "notes": "Standard floor bed. All systems nominal. Assigned to P-10003.",
        "assigned_patient_id": "P-10003",
        "bed_capabilities": ["pressure_mapping", "bed_exit_detection", "head_of_bed_angle"],
    },
    {
        "device_id": "D-7004",
        "device_type": "smart_bed",
        "model": "Baxter Progressa",
        "serial_number": "SBD-2026-004",
        "location": "Floor1-102",
        "floor": "Floor1",
        "firmware_version": "4.1.0",
        "latest_firmware": "4.1.0",
        "installation_date": "2025-05-20",
        "last_maintenance_date": "2026-03-10",
        "status": "active",
        "risk_profile": "healthy",
        "notes": "Recovery room bed. Assigned to P-10004.",
        "assigned_patient_id": "P-10004",
        "bed_capabilities": ["pressure_mapping", "bed_exit_detection", "head_of_bed_angle", "weight_sensing"],
    },
    {
        "device_id": "D-7005",
        "device_type": "smart_bed",
        "model": "Baxter Progressa",
        "serial_number": "SBD-2026-005",
        "location": "Floor1-118",
        "floor": "Floor1",
        "firmware_version": "2.5.1",
        "latest_firmware": "2.5.1",
        "installation_date": "2025-09-01",
        "last_maintenance_date": "2026-02-28",
        "status": "active",
        "risk_profile": "healthy",
        "notes": "Observation room bed. Assigned to P-10005.",
        "assigned_patient_id": "P-10005",
        "bed_capabilities": ["pressure_mapping", "bed_exit_detection"],
    },
]


# =============================================
# SMART BED TELEMETRY — real-time bed state data
# Stored in connected-care-device-telemetry table
# =============================================

SMART_BED_TELEMETRY = [
    {
        "device_id": "D-7001",
        "patient_id": "P-10001",
        "telemetry": {
            "bed_position": "supine",
            "head_of_bed_angle": 32,
            "rail_status": "both_up",
            "brake_status": "locked",
            "bed_exit_alarm": "armed",
            "last_bed_exit": "2026-03-30T02:14:00Z",
            "last_repositioned": "2026-03-29T23:45:00Z",
            "hours_since_reposition": 3.2,
            "restlessness_score": 7.2,
            "weight_kg": 58.5,
            "pressure_zones": {
                "sacrum": {"pressure_mmhg": 48, "duration_minutes": 192, "status": "high"},
                "left_heel": {"pressure_mmhg": 22, "duration_minutes": 192, "status": "normal"},
                "right_heel": {"pressure_mmhg": 25, "duration_minutes": 192, "status": "normal"},
                "left_shoulder": {"pressure_mmhg": 18, "duration_minutes": 45, "status": "normal"},
                "right_shoulder": {"pressure_mmhg": 30, "duration_minutes": 192, "status": "elevated"},
            },
            "braden_score": {
                "total": 12,
                "sensory_perception": 2,
                "moisture": 2,
                "activity": 1,
                "mobility": 2,
                "nutrition": 3,
                "friction_shear": 2,
                "risk_level": "HIGH",
            },
            "battery_level": 92,
            "connectivity_status": "connected",
        },
    },
    {
        "device_id": "D-7002",
        "patient_id": "P-10002",
        "telemetry": {
            "bed_position": "left_lateral",
            "head_of_bed_angle": 28,
            "rail_status": "both_up",
            "brake_status": "locked",
            "bed_exit_alarm": "armed",
            "last_bed_exit": "2026-03-30T06:30:00Z",
            "last_repositioned": "2026-03-30T04:15:00Z",
            "hours_since_reposition": 3.5,
            "restlessness_score": 4.1,
            "weight_kg": 82.3,
            "pressure_zones": {
                "sacrum": {"pressure_mmhg": 15, "duration_minutes": 30, "status": "normal"},
                "left_hip": {"pressure_mmhg": 42, "duration_minutes": 210, "status": "high"},
                "left_shoulder": {"pressure_mmhg": 35, "duration_minutes": 210, "status": "elevated"},
                "right_heel": {"pressure_mmhg": 12, "duration_minutes": 30, "status": "normal"},
                "right_shoulder": {"pressure_mmhg": 10, "duration_minutes": 30, "status": "normal"},
            },
            "braden_score": {
                "total": 14,
                "sensory_perception": 3,
                "moisture": 3,
                "activity": 2,
                "mobility": 2,
                "nutrition": 2,
                "friction_shear": 2,
                "risk_level": "MODERATE",
            },
            "battery_level": 87,
            "connectivity_status": "connected",
        },
    },
    {
        "device_id": "D-7003",
        "patient_id": "P-10003",
        "telemetry": {
            "bed_position": "supine",
            "head_of_bed_angle": 35,
            "rail_status": "left_up",
            "brake_status": "locked",
            "bed_exit_alarm": "armed",
            "last_bed_exit": "2026-03-30T07:00:00Z",
            "last_repositioned": "2026-03-30T06:30:00Z",
            "hours_since_reposition": 1.2,
            "restlessness_score": 2.5,
            "weight_kg": 65.0,
            "pressure_zones": {
                "sacrum": {"pressure_mmhg": 20, "duration_minutes": 72, "status": "normal"},
                "left_heel": {"pressure_mmhg": 15, "duration_minutes": 72, "status": "normal"},
                "right_heel": {"pressure_mmhg": 14, "duration_minutes": 72, "status": "normal"},
                "left_shoulder": {"pressure_mmhg": 12, "duration_minutes": 72, "status": "normal"},
                "right_shoulder": {"pressure_mmhg": 13, "duration_minutes": 72, "status": "normal"},
            },
            "braden_score": {
                "total": 18,
                "sensory_perception": 3,
                "moisture": 3,
                "activity": 3,
                "mobility": 3,
                "nutrition": 3,
                "friction_shear": 3,
                "risk_level": "LOW",
            },
            "battery_level": 95,
            "connectivity_status": "connected",
        },
    },
    {
        "device_id": "D-7004",
        "patient_id": "P-10004",
        "telemetry": {
            "bed_position": "right_lateral",
            "head_of_bed_angle": 25,
            "rail_status": "both_up",
            "brake_status": "locked",
            "bed_exit_alarm": "off",
            "last_bed_exit": "2026-03-30T06:45:00Z",
            "last_repositioned": "2026-03-30T07:00:00Z",
            "hours_since_reposition": 0.7,
            "restlessness_score": 1.8,
            "weight_kg": 76.2,
            "pressure_zones": {
                "sacrum": {"pressure_mmhg": 10, "duration_minutes": 42, "status": "normal"},
                "right_hip": {"pressure_mmhg": 22, "duration_minutes": 42, "status": "normal"},
                "right_shoulder": {"pressure_mmhg": 18, "duration_minutes": 42, "status": "normal"},
                "left_heel": {"pressure_mmhg": 8, "duration_minutes": 42, "status": "normal"},
                "left_shoulder": {"pressure_mmhg": 6, "duration_minutes": 42, "status": "normal"},
            },
            "braden_score": {
                "total": 20,
                "sensory_perception": 4,
                "moisture": 3,
                "activity": 3,
                "mobility": 4,
                "nutrition": 3,
                "friction_shear": 3,
                "risk_level": "LOW",
            },
            "battery_level": 98,
            "connectivity_status": "connected",
        },
    },
    {
        "device_id": "D-7005",
        "patient_id": "P-10005",
        "telemetry": {
            "bed_position": "supine",
            "head_of_bed_angle": 40,
            "rail_status": "none",
            "brake_status": "locked",
            "bed_exit_alarm": "off",
            "last_bed_exit": "2026-03-30T07:15:00Z",
            "last_repositioned": "2026-03-30T07:15:00Z",
            "hours_since_reposition": 0.5,
            "restlessness_score": 1.2,
            "weight_kg": 62.8,
            "pressure_zones": {
                "sacrum": {"pressure_mmhg": 18, "duration_minutes": 30, "status": "normal"},
                "left_heel": {"pressure_mmhg": 10, "duration_minutes": 30, "status": "normal"},
                "right_heel": {"pressure_mmhg": 11, "duration_minutes": 30, "status": "normal"},
                "left_shoulder": {"pressure_mmhg": 9, "duration_minutes": 30, "status": "normal"},
                "right_shoulder": {"pressure_mmhg": 9, "duration_minutes": 30, "status": "normal"},
            },
            "braden_score": {
                "total": 21,
                "sensory_perception": 4,
                "moisture": 4,
                "activity": 3,
                "mobility": 4,
                "nutrition": 3,
                "friction_shear": 3,
                "risk_level": "LOW",
            },
            "battery_level": 100,
            "connectivity_status": "connected",
        },
    },
]
